#!/bin/bash
cd "$(dirname "$(realpath "$0")")" || exit
#------------------------------------------------------------------------------

BASE_CASE_PATH="$(realpath !baseCase!)"
for p in $BASE_CASE_PATH/processor*/; do
    ln -s $p 
done

#------------------------------------------------------------------------------
